// Generated by CoffeeScript 1.7.1
(function() {
  var app, cs, express, helpers, restrict, routes;

  express = require('express');

  app = express();

  routes = require('./routes.js');

  helpers = require('express-helpers')(app);

  cs = require('client-sessions');

  app.set('view engine', 'ejs');

  app.set('views', __dirname + '/views');

  app.use(express["static"](__dirname, 'public'));

  app.use(express.bodyParser());

  app.use(express.cookieParser('joey'));

  app.use(express.session());

  app.use(cs({
    secret: 'verysecret',
    cookieName: 'sesh',
    duration: 24 * 60 * 60 * 1000
  }));

  app.use(app.router);

  restrict = function(req, res, next) {
    if (req.sesh.user_id) {
      return next();
    } else {
      req.session.error = 'fail';
      return res.redirect('/login');
    }
  };

  app.get('/', routes.home);

  app.get('/login', routes.login);

  app.post('/login', routes.plogin);

  app.get('/signup', routes.signup);

  app.post('/signup', routes.psignup);

  app.get('/link', routes.link);

  app.post('/link', routes.plink);

  app.get('/user/:id', restrict, routes.user);

  app.get('/logout', routes.logout);

  app.get('/test', routes.test);

  app.listen(1337, function() {
    console.log('listening on port 1337');
  });

}).call(this);
