// Generated by CoffeeScript 1.7.1
(function() {
  var client, redis;

  redis = require('redis');

  client = redis.createClient();

  client.auth('');

  console.log('welcome ~~/\~~');

  client.on('error', function(err) {
    console.log('error: ' + err);
  });


  /*
  client.hmset('user:2', 
  	'username': 'joe'
  	'email': 'jo4reel@yahoo.com'
  	'no_links': 1
  )
  
  client.hmset('user:3',
  	'username': 'ezzie'
  	'email': 'ez@gmail.com'
  	'no_links': 0
  )
   */

  client.hgetall('user:2', function(err, replies) {
    if (err) {
      console.log(err);
    }
    return console.log(replies);
  });

  client.quit();

}).call(this);
