// Generated by CoffeeScript 1.7.1
(function() {
  var hash, user;

  hash = require('./utils/nh').hasher;

  user = {};

  user.name = 'joe';

  user.email = 'jo4reel@yahoo.com';

  user.password = 'secret';

  hash({
    plaintext: user.password
  }, function(err, result) {
    var salt;
    if (err) {
      console.log(err);
    }
    user.salt = result.salt.toString('hex');
    user.key = result.key.toString('hex');
    console.log(user.salt);
    console.log(user.key);
    console.log(typeof user.salt);
    salt = new Buffer(user.salt, 'hex');
    hash({
      plaintext: user.password,
      salt: salt
    }, function(err, result) {
      if (err) {
        console.log(err);
      }
      if (result.key.toString('hex') === user.key) {
        console.log('YES');
      }
    });
  });

}).call(this);
