// Generated by CoffeeScript 1.7.1
(function() {
  var cs;

  cs = function(name) {
    return function(req, res, next) {
      req.session = req.signedCookies[name] || {};
      res.on('header', function() {
        return res.signesCookie(name, req.session, {
          signed: true
        });
      });
      next();
    };
  };

  module.exports = cs;

}).call(this);
