// Generated by CoffeeScript 1.7.1
(function() {
  var getConnection, mysql, pool;

  mysql = require('mysql');

  pool = mysql.createPool({
    host: 'testdb.cxploeysj4ic.us-west-2.rds.amazonaws.com',
    user: 'joeatt',
    database: 'testdb',
    password: 'qwerty123'
  });

  getConnection = function(callback) {
    pool.getConnection(function(err, conn) {
      if (err) {
        callback(err);
      }
      callback(null, conn);
      conn.release();
    });
  };

  module.exports.findLinksByUser = function(user, sql, callback) {
    getConnection(function(err, conn) {
      if (err) {
        callback(err);
      }
      conn.query(sql, [user], function(err, result) {
        if (err) {
          callback(err);
        }
        callback(null, result);
      });
    });
  };

  module.exports.makeLink = function(link, callback) {
    getConnection(function(err, conn) {
      if (err) {
        callback(err);
      }
      conn.query('insert into links set ?', link, function(err, result) {
        if (err) {
          callback(err);
        }
        callback(null, result);
      });
    });
  };

  module.exports.findUser = function(user, sql, callback) {
    getConnection(function(err, conn) {
      if (err) {
        callback(err);
      }
      conn.query(sql, [user], function(err, results) {
        if (err) {
          callback(err);
        }
        callback(null, results);
      });
    });
  };

  module.exports.makeUser = function(user, callback) {
    getConnection(function(err, conn) {
      if (err) {
        callback(err);
      }
      conn.query('select user_id from users where username = ? or email= ?', [user.username, user.email], function(err, results) {
        if (err) {
          callback;
        }
        if (results.length === 0) {
          conn.query('insert into users set ?', user, function(err, results) {
            if (err) {
              callback(err);
            }
            callback(null, results);
          });
        }
      });
    });
  };

}).call(this);
